import type { Metadata } from "next";
import {Nunito_Sans, Nunito } from "next/font/google";
import "./globals.css";
import clsx from "clsx";


const nunito_Sans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito_sans",
  display: "swap",
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(nunito.className, nunito_Sans.className)}>
      <body>{children}</body>
    </html>
  );
}
